### ISSUE TITLE
[doit] missing task for building the website with

### ISSUE THREAD

**Issue by ibressler** [BAMresearch/Reproducible-Science#12]
Hello,
I am new to _doit_ but it seems `doit list` should show a task for building the website which is defined in `dodo.py` but it does not have a name. For example:
```
--- a/dodo.py
+++ b/dodo.py
@@ -9,6 +9,7 @@ targets = [f + ".rst" for f in files]
 def task_website():
     pages = glob.glob("*.md")
     return {
+        "basename": "build website",
         "file_dep": pages + targets + ["conf.py", "index.rst"],
         "actions": ["sphinx-build . .build"],
```

Will produce
```
$ doit list
build website           
convert via to_rst.py   In an attempt of "literate programming", we directly use a documented,
```

### Motivation
For contributing, you want to build the website (which is the sphinx generated documentation) locally to see your changes. With a clone on macOS in a Python 3.8 virtual environment, you'll get
```
$ doit auto
Traceback (most recent call last):
  File "/Users/ingo/.py38/lib/python3.8/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
[...]
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
```
This is a problem with `doit`  and [how it uses the multiprocessing module](https://github.com/GoogleCloudPlatform/gsutil/issues/961#issuecomment-604648510). It can be avoided by disabling parallel processing:
```
$ doit -n 1 "build website"
```
Which is where the missing task comes into play.
Perhaps, there is a better way to run doit single-threaded, but it's the first one I found.

Thanks & best whishes
Ingo

**Comment by Psirus** [comment]
Thanks for your input. Unfortunately, I don't know if there is anything we can do about that multiprocessing bug, other than using your workaround. As for the task, it uses the name from the function definition, so `def task_website():` becomes `website`, and when I run `doit list`, I get:
~~~
convert via to_rst.py   In an attempt of "literate programming", we directly use a documented,
website 
~~~
That is a bit confusing, but the second line is actually the website task. So without modifying the `dodo.py` you could call `doit -n 1 website`.

**Comment by ibressler** [comment]
Thanks for the feedback and clarification!

Good to know, I mistook the 'website' in the last line for the 
continuation of the previous line because of the trailing comma (,) :/ 
sorry!

Am 23.10.20 um 17:17 schrieb Christoph Pohl:
